### PR TITLE
allow to use object argument in promise api. 

### PR DESCRIPTION
**Pull request by sidorares**
see #405 for details

### CODE REVIEW

**Comment by sidorares** [comment]
@felixfbecker can you review this?

**Comment by felixfbecker** [comment]
@sidorares Thanks for taking on this so quickly.

Ran the tests against your fixes: https://travis-ci.org/felixfbecker/node-sql-template-strings/jobs/160912369#L626

However, `pool.execute()` still doesn't work. You only changed `query`, but [`query` worked fine already before](https://travis-ci.org/felixfbecker/node-sql-template-strings/jobs/160755119#L615).

Even more, non-promise `pool.execute` now fails aswell? Maybe this was introduced by another commit on master not in this PR?

```
     Uncaught TypeError: Connection.statementKey is not a function
      at Prepare.start (node_modules/mysql2/lib/commands/prepare.js:25:25)
      at Prepare.Command.execute (node_modules/mysql2/lib/commands/command.js:38:20)
      at PoolConnection.Connection.handlePacket (node_modules/mysql2/lib/connection.js:361:28)
      at PoolConnection.Connection.handlePacket (node_modules/mysql2/lib/connection.js:367:12)
      at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:87:66)
      at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:45:12)
      at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:94:29)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:543:20)
```

**Comment by sidorares** [comment]
oh, maybe this was introduced with #404. I'll try to clone your repo and run tests locally

**Comment by sidorares** [comment]
ok found issue, I forgot to change promisified versions of pool.query and pool.execute adding this now. atm promise.js is not very DRY

**Comment by sidorares** [comment]
@felixfbecker `node-sql-template-strings#integration-tests` mysql2 tests now pass on my computer locally

File: promise.js [hunk 1]
```diff
@@ -79,25 +90,35 @@ function createPool (opts) {
 
     query: function (sql, args) {
       return new Promise(function (resolve, reject) {
-        corePool.query(sql, args, function (err, rows, fields) {
+        var done = function (err, rows, fields) {
```
Comment (felixfbecker) [inline promise.js]: For some DRY how about
```js
function queryDoneCb(resolve, reject) {
  return function(err, rows, fields) {
    if (err) {
      reject(err)
    } else {
      resolve([rows, fields])
    }
  }
}
```
That could be used in 4 places (query, promise) x (query, execute)
```js
var done = doneCb(resolve, reject)
```

File: test/integration/test-promise-wrappers.js [hunk 2]
```diff
@@ -52,8 +52,31 @@ function testErrors () {
   });
 }
 
+function testObjParams () {
+  var connResolved;
+  var connPromise = createConnection(config).then(function (conn) {
```
Comment (felixfbecker) [inline test/integration/test-promise-wrappers.js]: To prevent regressions it would be nice if you could test this against the pool aswell (I do this in my tests aswell with a simple loop)

**Comment by felixfbecker** [comment]
Tests pass 🎉 
https://travis-ci.org/felixfbecker/node-sql-template-strings/jobs/160912369

**Comment by felixfbecker** [comment]
Please ping me when this is released :)

File: test/integration/test-promise-wrappers.js (hunk 2 above)
Comment (sidorares) [inline test/integration/test-promise-wrappers.js]: yes, I'll add tests as part of this pr

**Comment by sidorares** [comment]
@felixfbecker I'll finish this pr tonight and we'll probably have v1.1.0 out in maybe 24 hrs from now

**Comment by sidorares** [comment]
> Please ping me when this is released :)

@felixfbecker you probably already noticed, but pinging anyway :) published 4 days ago
