### ISSUE TITLE
Error on deno compile from version 3.4.1

### ISSUE THREAD

**Issue by qihangnet** [sidorares/node-mysql2#3136]
Starting from version 3.4.1, an error occurs when build the application using `deno compile`.

TS2339 [ERROR]: Property 'execute' does not exist on type 'PoolConnection'
TS2339 [ERROR]: Property 'query' does not exist on type 'PoolConnection'
TS2339 [ERROR]: Property 'execute' does not exist on type 'Connection'.
TS2339 [ERROR]: Property 'query' does not exist on type 'Connection'.

……

**Comment by qihangnet** [comment]
[This repository](/qihangnet/deno2-mysql2-issues-reproduction) serves as a minimal example to reproduce these issues.

**Comment by shunkica** [comment]
I can not get it to work on any version of `deno >= 2.2`
The most obvious difference is that deno 2.2 updates typescript version to  5.7

My error is similar:

```
import mysql from "mysql2/promise";
const pool: MysqlPool = mysql.createPool({...})
await pool.execute(...);
```

> TS2339 [ERROR]: Property 'execute' does not exist on type 'Pool'.

On `deno <= 2.1` the same code works

**Comment by wellwelwel** [comment]
Hi, @shunkica. The problem is that **MySQL2** needs a development dependency for **TypeScript** (`@types/node`):

> https://github.com/sidorares/node-mysql2/blob/5723407944ccce4828ae73339669ed763f5d4285/README.md#L85-L89

Since **Deno** doesn't have an explicit way of installing development dependencies, `@types/node` would have to be imported directly, for example:

```json
{
  "imports": {
    "mysql2": "npm:mysql2",
    "@types/node": "npm:@types/node"
  }
}
```

Then, reference it in the connection file:

```ts
/// <reference types="npm:@types/node" />

import mysql from "mysql2/promise";

// ...
```

**Comment by wellwelwel** [comment]
Hmm, there's no need to install `@types/node` in _deno.json_. By using `/// <reference types="npm:@types/node" />` in the connection file, **Deno** downloads the types without it being listed as a direct dependency:

```sh
Task build deno compile --allow-net --output ../dist/mysql2-341 main.ts
Compile file:///Users/weslleyaraujo/Desktop/deno2-mysql2-issues-reproduction/mysql2-3-4-1/main.ts to ../dist/mysql2-341

Embedded Files

mysql2-341
├─┬ .deno_compile_node_modules (4.27MB - 4.22MB unique)
│ └─┬ localhost (4.27MB - 4.22MB unique)
│   ├── @types/node/* (2.19MB - 2.19MB unique) <-- HERE
│   ├── denque/2.1.0/* (30.22KB - 30.19KB unique)
│   ├── generate-function/2.3.1/* (9.27KB - 9.22KB unique)
│   ├── iconv-lite/0.6.3/* (348.58KB - 348.54KB unique)
│   ├── is-property/1.0.2/* (13.83KB - 13.82KB unique)
│   ├── long/5.3.2/* (136.46KB - 126.59KB unique)
│   ├─┬ lru-cache (755.72KB - 714.03KB unique)
│   │ ├── 7.18.3/* (131.18KB - 131.16KB unique)
│   │ └── 8.0.5/* (624.54KB - 582.87KB unique)
│   ├── mysql2/3.4.1/* (670.3KB - 669.41KB unique)
│   ├── named-placeholders/1.1.3/* (7.44KB)
│   ├── safer-buffer/2.1.2/* (41.98KB - 41.95KB unique)
│   ├── seq-queue/0.0.5/* (18.81KB - 18.75KB unique)
│   ├── sqlstring/2.3.3/* (17.48KB - 17.46KB unique)
│   └── undici-types/6.20.0/* (82.25KB - 81.81KB unique)
├── Database.ts (2.81KB)
└── mysql2-3-4-1/main.ts (302B)

Files: 4.25MB
Metadata: 1.94KB
Remote modules: 12B
```

@qihangnet, thanks for the reproduction examples 🤝
